package com.hospital.hms.provider.entity;

public enum WorkflowType {
    PATIENT_ROUNDS, CLINICAL_DOCUMENTATION, ORDER_ENTRY, 
    MEDICATION_REVIEW, LAB_REVIEW, IMAGING_REVIEW, 
    DISCHARGE_PLANNING, EMERGENCY_RESPONSE, CONSULTATION
}
