package com.hospital.hms.procedure.entity;

public enum ProcedureType {
    CARDIAC, ORTHOPEDIC, NEUROLOGICAL, GENERAL, PLASTIC, UROLOGICAL, 
    GYNECOLOGICAL, OPHTHALMIC, ENT, THORACIC, VASCULAR, PEDIATRIC, 
    EMERGENCY, MINIMALLY_INVASIVE, ROBOTIC, TRANSPLANT, OTHER
}
